### ISSUE TITLE
Add headers to the generated client

### ISSUE THREAD

**Issue by DAddYE** [thriftrw/thriftrw-go#104]
At @uber we need to pass some headers to the generated http client. Would be nice to do so in a programmatically way without edit by hands every time the generated code.

**Comment by abhinav** [comment]
The intention is to have configurable code generation schemes. TChannel, Ringpop, and YARPC have their own ideas of how the generated code for a service looks. It's not out of question to have an HTTP code generator which will allow that. Note that we can't do HTTP until https://github.com/thriftrw/thriftrw-go/issues/105 is resolved. The payload won't be compatible with Apache Thrift without that.

**Comment by abhinav** [comment]
YARPC+ThriftRW supports request and response headers. Plus with the plugin system, someone else can write a TChannel/Ringpop/Plain HTTP plugin which also supports request/response headers. Resolving.
