### ISSUE TITLE
API version tags

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#115]
We should include a runtime constant that specifies which version of the generated code the current version of the library can work with. This should help resolve issues where the compiler version doesn't match the library version

**Comment by prashantv** [comment]
:+1: should the generated code and library be defensive about this, and return an error on creation if there's some mismatch?

we might want something like semver for the version tags if we want that.

**Comment by breerly** [comment]
Yup :+1:

**Comment by abhinav** [comment]
Taken care of by https://github.com/thriftrw/thriftrw-go/pull/247
