### ISSUE TITLE
Add .nocover files in all generated dirs

### ISSUE THREAD

**Issue by breerly** [thriftrw/thriftrw-go#130]
This excludes these dirs from code coverage systems like coveralls.

Created https://github.com/uber/tchannel-go/issues/375 as well.

**Comment by abhinav** [comment]
The `.nocover` thing is not standard. It's just a hack in our `cover.sh` script: https://github.com/yarpc/yarpc-go/blob/master/scripts/cover.sh#L17

**Comment by breerly** [comment]
Right - but doesn't it at least give people *something* they can hook onto? I imagine a guide where we illustrate how people could ignore all dirs with `.nocover`.

**Comment by abhinav** [comment]
As of now, ThriftRW generates only one directory per Thrift file. I don't think we need this. Users who care about it can hack together a fairly simplistic shell one liner to do this. Re-open if you disagree.
