### ISSUE TITLE
Define 1.0.0 Milestone

### ISSUE THREAD

**Issue by breerly** [thriftrw/thriftrw-go#204]
I'd like to plan a `1.0.0` milestone now, so that we can start understanding how far away that is.

**Comment by breerly** [comment]
@abhinav can you take a stab at that? I'll take yarpc :)

**Comment by breerly** [comment]
Created the milestone, now we just need to populate it:

https://github.com/thriftrw/thriftrw-go/milestone/2

**Comment by abhinav** [comment]
We'll be releasing soon
