### ISSUE TITLE
Code generation should capitalize abbreviations

### ISSUE THREAD

**Issue by APTy** [thriftrw/thriftrw-go#207]
From convo with @abhinav

The [Go style guide](https://github.com/golang/go/wiki/CodeReviewComments#initialisms) suggests that abbreviations (or initialisms, as they call them) should be in all caps. But they also go on to say:

> Code generated by the protocol buffer compiler is exempt from this rule.

And I think there's a good reason for that. For example, if we have `foo.thrift`:
``` thrift
struct User {
    1: required i32 ZIPCode
    2: required i32 groupId
    3: required bool hidden
}
```
We should definitely see the capitalization `User.ZIPCode` in our Go object, since that stays true to the thrift definition (this is not currently the case).

I'm less sure if we can extend this to capitalize params like `groupId` -> `GroupID` without accidentally capitalizing `hidden` -> `HIDden`, which is probably why generation tools are generally exempt from the capitalization rule.

**Comment by abhinav** [comment]
We leave attributes that are capitalized alone. In the above example, we leave `ZIPCode` as-is. Changing `groupId` to `groupID` is a bit complicated with a lot of corner cases. It's simpler to leave it as the user specified.

Based on our conversation offline: There is a bug in thriftrw where all-caps attributes which are not known abbreviations are converted into PascalCase. We should leave those alone too.

**Comment by abhinav** [comment]
Related: https://github.com/thriftrw/thriftrw-go/issues/208

**Comment by abhinav** [comment]
This is sort of resolved to the extent that it's feasible to do so. Handling all possible cases for this is not very easy. Maybe we can address it with a `go.name` annotation. See also #223.
