### ISSUE TITLE
ThriftRW-go should marshall enums to JSON as the name string

### ISSUE THREAD

**Issue by kriskowal** [thriftrw/thriftrw-go#214]
State of things:

Regardless of implementation, the intent is for the user to use the name of an enum and not to cast a number out of thin air. The number value is intended for the wire, and the name intended for code.

In Java, Python, and Go, enums are named numbers in code. The generated code produces a constant with the corresponding number. In JavaScript, consequently TCurl, enums values are expressed with the string name and only represented as a number on the wire. This is to allow users to express the name in both TCurl and in code, which is especially important because the idiom in JavaScript is to express Thrift requests and responses without necessarily importing the IDL model.

Consequently, when marshaling a Thrift model in Go to JSON, it should produce JSON suitable for use in JavaScript. Enum values should marshal to the string name.

**Comment by abhinav** [comment]
One issue with using strings as enums in JSON is what you read for unrecognized enums. With integers, you can still read the value, and the consuming code can still have a default catch-all case for unknown enum values. With strings, you'll basically have to error out. This is a largely backwards-breaking approach to when new enum items are added.

**Comment by prashantv** [comment]
For deserialization, we should definitely support both integer and name. Can we do the same in thriftrw-node/tcurl? Name is more convenient for users, but number should be supported for the unknown enum case.
