### ISSUE TITLE
Constant naming

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#215]
As of #209,

```
const i32 VERSION = 1
```

Generates,

```
const VERSION int32 = 1
```

But

```
const i32 APP_VERSION = 1
```

Generates,

```
const AppVersion int32 = 1
```

We should either always PascalCase constants if they're not known abbreviations, or just revert #209 and go back to known-abbreviations only.

**Comment by prashantv** [comment]
+1 to treating constants the same way as enums, and always using PascalCase
