### ISSUE TITLE
Name normalization collisions

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#223]
Consider,

```
struct User {
  1: required string firstName
  2: required string first_name
}
```

This will fail or generate invalid code because both attributes become `FirstName`. We need to account for collisions in attribute naming when normalizing during code generation.

We can pick `FirstName2` for the second one by default and maybe allow overriding it with a `go.name` annotation.

```
struct User {
  1: required string firstName
  2: required string first_name (go.name = "OtherFirstName")
}
```

**Comment by bombela** [comment]
discussed offline:
 - we refuse to generate code if there is a collision
 - we use the attribute name whenever available (and fail if collision here as well)
 - attribute go.name will be enforced as Go style
