### ISSUE TITLE
Expose ToWire/FromWire interface

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#226]
All generated structs, typedefs, and enums implement this interface:

``` go
type Value interface { // Name TBD
    ToWire() (wire.Value, error)
    FromWire(wire.Value) error
}
```

We may want to expose this interface somewhere (`protocol.Value`?) explicitly.

**Comment by abhinav** [comment]
For comparison: Apache Thrift has a [`TStruct`](https://godoc.org/github.com/apache/thrift/lib/go/thrift#TStruct) type.

**Comment by abhinav** [comment]
There's no place where we need this yet.

**Comment by zichuanwang** [comment]
This is needed for thrift over HTTP. It's pretty common to have a helper serde function that's shared by different gateway APIs.

**Comment by abhinav** [comment]
@zichuanwang Could you elaborate on your use case? The methods are already exposed and since implementations don't have to explicitly declare which interfaces they implement, you can declare your own version of that interface and all ThriftRW-generated types will work with it. Is there a strong reason to have the type defined in ThriftRW Go itself?
