### ISSUE TITLE
Consider generating service structs in the same package as types

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#232]
Currently, for foo.thrift, we generate,

```
foo/
 |- types.go
 |- service/
     |- servicea/
         <service structs go here>
     |- serviceb/
         <service structs go here>
```

Since the `servicea` and `serviceb` packages import the `foo` package (which
defines the types declared in the Thrift file), you cannot generate the
client/server types that depend on the service structs in the `foo` package.
That is, you can't generate `foo.ServiceAClient` because it needs access to
`servicea.MyMethodArgs`, `servciea.MyMethodResult`, etc., and those types
depend on `foo.MyType`, which results in a cyclic import.

The service structs get generated in their dedicated package mostly to account
for naming collisions: MyMethodArgs and MyMethodResult should not collide with
a user-defined MyMethodArgs/MyMethodResult struct.

We could get away with this by using the prefix `$service$method` for the
args and result structs (and the helper), and making the code generator
slightly smarter by making it use `ServiceAMyMethodArgs2` if
`ServiceAMyMethodArgs` is taken by the user.

If we do this, the ServiceGenerator plugin API will have to be changed
slightly to also receive the name of the args and result structs for each
method.

**Comment by prashantv** [comment]
Should types that depend on the service structs also be generated under `servicea` or `serviceb` instead?

**Comment by abhinav** [comment]
That is one of the options you have today. That or generating under another package elsewhere (which is what YARPC does; it generates to `yarpc/$servicename{server,client}`). 

I mostly opened this to start the conversation about package structure. Issues with the current design are,

- It's impossible to have everything in a single package. So you definitely cannot offer an API similar to Apache Thrift.
- If the lower cased service name is the same as the thrift file name, you now have to deal with that package name collision every time you import something from both. YARPC side-steps this by using separate client and server packages.

I'm *mostly* okay with these tradeoffs but I would like for the problem to go away completely if possible.

**Comment by breerly** [comment]
@abhinav can you write some example code from the clients POV? I'd like to see what the API *feels* like to use.

Also, what would be required on the clients side to migrate?

**Comment by prashantv** [comment]
@abhinav and I had a quick offline chat. My main concern is that a single package would require service prefixes for every type. However, plugins can still generate subpackages for each Thrift service -- users wouldn't directly interact with the service types generated by thriftrw.

Given that, I'm fine with moving everything to a single package.

**Comment by abhinav** [comment]
@breerly This wouldn't necessarily affect the YARPC client API. It would
affect the API used by the generated client code.

Specifically, right now, `$service{server,client}` packages import both, the 
`$thriftFile` package and the `$thriftFile/service/$service` package. The
latter is imported to gain access to the Args and Result types and the Helpers.

The current generated code might look like,

    import ".../kv"
    import ".../kv/service/keyvalue"

    &keyvalue.SetValueArgs{
        Key: &kv.SetValueRequest{..}
    }


This would simplify it to,

    import ".../kv"
    
    &kv.SetValueArgs{Key: &kv.SetValueRequest{..}}

**Comment by breerly** [comment]
Ok, I'm onboard.

**Comment by bombela** [comment]
I guess we don't have many choices, we could have:

```
foo/types.go
foo/service/a
foo/server/a
foo/client/a
```

Which forces renaming imports all the time:

```
import foo/service/a as serviceA
import foo/server/a as serverA
import foo/client/a as clientA
```

Has the merit of being fairly consistent, but yes, you pretty much HAVE TO rename things.

We could make things slightly more self-named by doing:

```
foo/types.go
foo/service/fooServiceA
foo/server/fooServerA
foo/client/fooClientA
```

importing it like so:

```
import foo/service/fooServiceA
import foo/server/fooServerA
import foo/client/fooClientA
```
