### ISSUE TITLE
Enforce compatible version of generated code and thriftrw library

### ISSUE THREAD

**Issue by bombela** [thriftrw/thriftrw-go#246]
Right now the code generated by `./thriftw` is independent from the thriftrw library. But we need to use `thriftrw/wire` and eventually `thriftrw/protocol` with generated types in order to serialize/deserialize them.

We would like to prevent subtle bugs because of differences between the version of thriftrw used to generate the code and the version used at runtime.

#### Solution 1 - compile time

Possible solution is a compile time error based on missing const/variable containing the version in the name. In every generated file, we add:

```go
const _ = version.GenCodeCompatibleVersions.v3_4
```

And if `thrtiftrw/version.GenCodeCompatibleVersions.v3_4` doesn't exist, compilation will fail. The error might not be the most readable nor understandable, but has the merit of being unavoidable.

#### Solution 2 - runtime

We add a new generated file per generated go packages (ie: per generated directory), containing something like the following:

```go
func init() {
  version.IHaveBeenGeneratedWithThriftrwVersion(3, 4, 0)
}
```

The function `IHaveBeenGeneratedWithThriftrwVersion` in thriftrw is responsible for checking versions compatibility and panicking at startup. The error message can be made satisfyingly clear, in the expense of waiting until runtime to fail.

**Comment by abhinav** [comment]
Solution 2 has another advantage: By being part of the library, the version
match can be as liberal or as specific as we want. With the compile-time
check, we have to pick the granularity (major or minor version) in advance and
stick with it.

**Comment by bombela** [comment]
Very true.

**Comment by breerly** [comment]
Solution 2 makes more sense to me - we'll have more control over the user experience (error message) if it's not a compile time constraint.

**Comment by AlexAPB** [comment]
+1 for solution 2
