### ISSUE TITLE
plugin API version: Consider using semantic versioning

### ISSUE THREAD

**Issue by AlexAPB** [thriftrw/thriftrw-go#253]
Currently the plugin API version is just a single integer. This means that it's impossible to do updates to the plugin API that are backwards compatible with older versions.

For example, 0.4 adds a new field to Function. We should bump the API version for this to prevent plugins that depend on the OneWay attribute from failing, but this also means that plugins that don't care about that attribute will start failing unless they're recompiled with the new version of the library.

Using some sort of semantic versioning scheme would solve this. As in,

```
const i32 MAJOR_VERSION = 1
const i32 MINOR_VERSION = 0
const i32 PATCH_VERSION = 0
```

**Comment by abhinav** [comment]
Plugin handshakes now verify ThriftRW versions which is semver.
