### ISSUE TITLE
Enum not supported correctly

### ISSUE THREAD

**Issue by vivekrsharma** [thriftrw/thriftrw-go#297]
More context in https://github.com/yarpc/yarpc-java/pull/321. 

In gist, Given a enum Numberz - 

```
 enum Numberz
{
  ONE = 1,
  TWO,
  THREE,
  FIVE = 5,
  SIX,
  EIGHT = 8
}
```

The generated Go code typedefs Numberz to int32 and can deserialize from any int32 value.

``` 
type Numberz int32

func (v *Numberz) FromWire(w wire.Value) error {
	*v = (Numberz)(w.GetI32())
	return nil
}
```

However other language that supports thrift returns a null.

``` 
public static Numberz findByValue(int value) { 
    switch (value) {
      case 1:
        return ONE;
      case 2:
        return TWO;
      case 3:
        return THREE;
      case 5:
        return FIVE;
      case 6:
        return SIX;
      case 8:
        return EIGHT;
      default:
        return null;
    }
  }
```
The Go is expecting the server to construct Numberz(42), but this deserializes to null in Java.

**Comment by vivekrsharma** [comment]
@blampe @bombela @abhinav @breerly

**Comment by bombela** [comment]
If thrift says we must only accept enum that we know, then let's forbid parsing/serializing unknown values. Do you know where we can find any reference about that @vivekrsharma ?

**Comment by bombela** [comment]
The closest information I could find so far:
https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/generate/t_cpp_generator.cc#L590
https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/generate/t_go_generator.cc#L947
https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/generate/t_java_generator.cc#L442

It does look like the Java version is doing thing differently than C++ and Go. Both C++ and Go treat enums as simple numbers that eventually happen to have some named constants.

**Comment by bombela** [comment]
As discussed in person with @abhinav & @vivekrsharma the conclusion is a problem on apache thrift java side. Java enums are strict, but thrift enums are not (ie, a thrift enum is valid no matter if a an enum item exists for a given value or not). 

We have no choice, but to explicitly skip enum tests with unknown values against yarpc java.
