### ISSUE TITLE
Remove version from comment in generated code?

### ISSUE THREAD

**Issue by peter-edge** [thriftrw/thriftrw-go#300]
thriftrw makes a comment at the top of every file like `+// Code generated by thriftrw v1.2.0`. By having the version in there, this means that generated code will have a diff on every version change, ie https://github.com/yarpc/yarpc-go/pull/951. Should we remove the version from the comment?

**Comment by abhinav** [comment]
That won't solve anything. We also generate a check to verify that the generated code matches the library version the code is running against. See https://github.com/yarpc/yarpc-go/pull/951/files#diff-33955b1801d9e3d968fe21f1e01d2421

**Comment by peter-edge** [comment]
Well ya but then only that file will be updated, not every generated file.

**Comment by abhinav** [comment]
I don't feel strongly about the header but I would rather have that information there for the sake of debugging stale files. The cost of having the header is fairly low.

**Comment by peter-edge** [comment]
OK
