### ISSUE TITLE
int64 > 32127 can't be deserialized by thriftrw-node.

### ISSUE THREAD

**Issue by Willyham** [thriftrw/thriftrw-go#321]
Note that I am assuming that this is an issue with thriftrw-go because the thriftrw-node test suite defintely covers int64s larger than this.

Given:

```
struct Foo {
  1: optional i64 startTime;
}
```

Sending:

```
		x := int64(32128)
                &bar.Foo{
			StartTime: &x,
		}
```

Results in:

```
{ ThriftInvalidTypeidError: invalid typeid -65 of field::type; expects one of the values in TYPE
    at Object.createError [as InvalidTypeidError] (/kodenom/web/node_modules/error/typed.js:31:22)
    at skipType (/kodenom/web/node_modules/thriftrw/skip.js:90:40)
    at StructRW.poolReadFrom (/kodenom/web/node_modules/thriftrw/struct.js:418:22)
    at ListRW.poolReadFrom (/kodenom/web/node_modules/thriftrw/list.js:137:26)
    at StructRW.poolReadFrom (/kodenom/web/node_modules/thriftrw/struct.js:443:37)
    at StructRW.poolReadFrom (/kodenom/web/node_modules/thriftrw/struct.js:443:37)
    at StructRW.readFrom (/kodenom/web/node_modules/bufrw/base.js:76:10)
    at Object.fromBufferResult (/kodenom/web/node_modules/bufrw/interface.js:120:18)
    at StructRW.fromBuffer (/kodenom/web/node_modules/thriftrw/rw.js:38:18)
    at Request._callback (/kodenom/web/server/client.js:70:57)
```

However, sending: 

```
		x := int64(32127)
                &bar.Foo{
			StartTime: &x,
		}
```

Results in:

```
{"startTime":{"type":"Buffer","data":[0,0,0,0,0,0,125,127]}}
```

If it is relevant, this is thrift over HTTP.

**Comment by abhinav** [comment]
This is weird. We definitely test for this: https://github.com/thriftrw/thriftrw-go/blob/cb72e78f03ba500a64e1d49e0c83912a31666631/protocol/binary_test.go#L208-L219. Plus I doubt that we haven't sent a date past 32128 seconds through our system yet. That's just a few hours after epoch.

If you can give me a pice of code that reproduces this, I would greatly appreciate it. Alternatively, the raw bytes will do.

---

Also, are you sure this isn't an enveloping issue? Perhaps the server and client don't agree on whether there's a Thrift envelope?

**Comment by Willyham** [comment]
It could be an enveloping issue, but my assumption was that both thriftrw implementations don't use them by default. I've just created a test case for this and confirmed that whilst it works with `yab`, the node thriftrw still causes problems. Might be an issue on that side, but then again `yab` is probably using the same underlying library as the server, so I'd expect them to agree.

Sorry, the test is a little involved, so I've had to create an archive:

[issue.tar.gz](https://github.com/thriftrw/thriftrw-go/files/1218543/issue.tar.gz)

**Comment by Willyham** [comment]
cc @kriskowal from the thriftrw-node side of things. It might be that I'm using the wrong method to deserialize this.

The node side is doing:

```
const buf = new Buffer(res.body)
const body = thrift.Foo.bar.result.rw.fromBuffer(buf);
```

**Comment by abhinav** [comment]
Thanks for the repro @Willyham.

Capturing the output, when the Go program prints,

```
Returning  1502729999956297226
```

The following is sent in the HTTP response:

```
0C00 000A 0001 14DA C4F9 20B7 C60A 0000
```

Breaking the Thrift payload down,

```
0C 0000     // id = 0, type = struct (0: BarResponse -- return value)
  0A 0001   // id = 1, type = i64    (1: i64 baz)
    14DA C4F9 20B7 C60A // == 1502729999956297226
  00        // end BarResponse
00          // end response struct
```

So the response from ThriftRW Go is definitely a valid Thrift payload.

Adding a log line to the node program, I get the following when the Go program returns 1502730756905191463.

```
Decoding: 0c00000a000114efbfbdc5a95e6348270000
```

That is not a valid Thrift payload plus the actual i64 value appears to have been corrupted en route:

```
0C 0000     // id = 0, type = struct (0: BarResponse -- return value)
  0A 0001   // id = 1, type = i64    (1: i64 baz)
    14EF BFBD C5A9 5E63 // == 1508635221978340963 != 1502730756905191463
    4827        // ??
  00        // end BarResponse
00          // end response struct
```

I don't know enough about Node to know why the Buffer is corrupted.

**Comment by Willyham** [comment]
Thanks @abhinav I'll raise the issue on the thriftrw-node side.
