### ISSUE TITLE
Support . in name of enum

### ISSUE THREAD

**Issue by Raynos** [thriftrw/thriftrw-go#337]
When we have

```
enum AnEnum {
  com.java.an_enum
}
```

thriftrw-go will not be able to generate valid go code. `thriftrw-go` should remove the `.` from the identifier when it's generating the enum code.

**Comment by abhinav** [comment]
That's not a valid enum item name in ThriftRW or Apache Thrift.

```
$ thrift --gen py tmp.thrift
[ERROR:/Users/abg/dev/go/src/go.uber.org/dig/tmp.thrift:3] (last token was '}')
Identifier com.java.an_enum can't have a dot.
```

**Comment by Raynos** [comment]
Ok we will send a pull request and/or fork. Thanks.
