### ISSUE TITLE
ast.DefinitionInfo should include the location of the source code

### ISSUE THREAD

**Issue by DAddYE** [thriftrw/thriftrw-go#349]
Hi!

Now each `ast.Definition` has `func Info() DefinitionInfo()` which returns a struct with `Name` and `Line` of the `Definition`, however, would be amazing if instead of the line we have a `Location[int, int]` (i.e [token.Position](https://golang.org/pkg/go/token/#Position)) this would allow me to select back the text range in the source file and do extra parsing.

**Comment by abhinav** [comment]
Hey, it's not quite clear what you're asking. Did you want column numbers as
well? Or do you want the start and end positions?

The first would be possible by doing some extra book keeping in the lexer and
passing it on to the constructed nodes similar to the line number.

The latter is possible but significantly more difficult because it requires a
lot more changes to the parser and lexer.

If you expand on the use case a bit, we can maybe figure out a work around.

**Comment by jparise** [comment]
@abhinav would you prefer to see this added as distinct `Line` and `Column` fields:

```go
type DefinitionInfo struct {
	Name   string
	Line   int
    Column int
}
```

... or by moving to an embedded `Position`?

```go
type DefinitionInfo struct {
    Position
	Name string
}
```

**Comment by abhinav** [comment]
Hey, sorry for the delay. 
Switching to embedding might be considered a breaking change. 

I would lean with the first option, but an alternative is a new Pos field, with Line deprecated in favor of it. We'd still fill Line for backwards compatibility, but Pos is what should be used going forward. Something like this?

```go
type DefintiionInfo struct {
  Name string

  // Deprecated: Use Pos.
  Line int

  // Position of the definition in the source file.
  Pos Position
}
```

**Comment by jparise** [comment]
I think it will probably end up being more trouble maintaining both `Line` and `Pos` together. The parser tests will become pretty verbose.

We can always produce a `Position` from `Line` and `Column` fields (which I'll offer through a `nodeWithPosition` interface and an `ast.Pos(ast.Node)` function).

At a future point when we can break some backwards compatibility, we could drop `Line` and `Column` in favor of a single `Pos`, or decide to embed `Position`.
