### ISSUE TITLE
Support enum item renaming

### ISSUE THREAD

**Issue by cl1337** [thriftrw/thriftrw-go#362]
### 1: What feature wanted:

for thrift files with reserved keyword: `function`, `end`, `native` .. etc
```thrift
enum TestEnum {
    function
    end
    native
}
```
we want to be able to separate naming from its string value in `UnmarshalText` with some labels:
```thrift
enum TestEnum {
    function1 (go.wire.label = "function")
    end1 (go.wire.label = "end")
    native (go.wire.label = "native")
}
```
and generate `type.go` with following `UnmarshalText` function 
```go
func (v *TestEnum) UnmarshalText(value []byte) error {
	switch string(value) {
	case "function":
		*v = TestEnumTypeFunction1
		return nil
	case "end":
		*v = TestEnumTypeEnd1
		return nil
        case "native":
		*v = TestEnumTypeNative1
		return nil 
	default:
		return fmt.Errorf("unknown enum value %q for %q", value, "TestEnum")
	}
}
```

### 2: why we need this

we're migrating one of our major nodejs service to go, because thriftrw node and thriftrw go have different opinion about what's a valid thrift file (e.g. keyword mentioned above), a lot of thrift files that are currently used on production cannot be migrate to go

we're not allowed to change what name was specified in thrift files, which will require a non-trivial and never end migration, we need to tweak thrift compile to make sure we can still use same name

all reserved keywords [here](https://github.com/thriftrw/thriftrw-go/blob/16ef2f392e3ca08ea35e44f95e9b5831ea2356dd/idl/internal/lex.rl#L106) 

### 3: proposed fix

Similar to https://github.com/thriftrw/thriftrw-go/issues/293, that separates concern of schema naming and actual data on the wire, we could instead of using `.Name` [here](https://github.com/thriftrw/thriftrw-go/blob/9ce01c65792c9e633eb9086985fde8f28470214f/gen/enum.go#L101), infer name from labels like `go.label` annotation

Happy to put PR out if this issue makes sense to you, also open to other good ideal to address this, thanks in advance

**Comment by abhinav** [comment]
This sounds reasonable. The same annotation can be supported on struct fields to override their name in the struct's JSON representation and the Zap marshalers (#361).

**Comment by kriskowal** [comment]
Reasonable.

**Comment by cl1337** [comment]
https://github.com/thriftrw/thriftrw-go/pull/363
