### ISSUE TITLE
Enforce unambiguous case

### ISSUE THREAD

**Issue by kriskowal** [thriftrw/thriftrw-go#7]
Across languages, any identifier may be remapped from PascalCase or camelCase to a convention acceptable for an identifier class in its particular language. For example, Python remaps camelCase methods to snake_case. Go must remap camelCase to PascalCase on methods for them to be public. As a consequence, no name space can have two names that vary only by their case convention. This needs to be enforced to guarantee portability.

**Comment by abhinav** [comment]
We do this now. We normalize names to lower case when checking conflicts.
