### ISSUE TITLE
Easier dispatch on unions

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#79]
Currently, if you want to branch on which field of a union is set, you'd have to do something like this:

    if myUnion.field1 != nil {
        // ...
    } else if myUnion.field2 != nil {
        // ...
    } else if myUnion.field3 != nil {
        // ...
    }

It would be nicer if we provided an easier way to branch on this. Perhaps a corresponding implicit enum for each union?

    switch /* TBD */ {
        case MyUnionField1: ...
        case MyUnionField2: ...
        case MyUnionField3: ...
    }

A concern about this is the amount of names we'd end up reserving in the namespace. Maybe we can put these in a different namespace scope while still keeping a reasonable API.

**Comment by kriskowal** [comment]
My take is that we should keep to the if/else train for this. I suspect anything else is too clever, including the clever thing I did in thriftrw-node that hopefully nobody knows about.

**Comment by prashantv** [comment]
Didn't think about reserving the names, in that case, +1 to Kris, not sure it's worth this. The user can do:
```go
switch u := getUnion() {
case u.Field1 != nil:
  // ...
case u.Field2 != nil:
  // ...
default:
  // ...
}
```

Which is probably good enough

**Comment by abhinav** [comment]
Alright. Closing.
